config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  get 'pages/loginpage'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'users#index'
  
  resources :users do
    member do
     get :following, :followers
    end
  end
  
  resources :matching, only: [:index, :show]
  resources :profiles
  resources :relationships, only: [:index ,:create, :destroy]
  resources :liked, only: [:index]
  mount ActionCable.server => '/cable'
end

app/controllers/matching_controller.rb
class MatchingController < ApplicationController
  before_action :authenticate_user!, only: [:index, :show]
  before_action :only_profile_user,  only: [:index, :show]
  
  def index
    @users = User.matching(current_user).page(params[:page]).per(12)
  end

  def show
    session[:user_id] = current_user.id
    @user = User.find(params[:id])
    @room_id = message_room_id(current_user,@user)
    @messages = Message.recent_in_room(@room_id)
  end
  
  private
  
    def message_room_id(first_user, second_user)
      first_id = first_user.id.to_i
      second_id = second_user.id.to_i
      if first_id < second_id
        "#{first_user.id}-#{second_user.id}"
      else
        "#{second_user.id}-#{first_user.id}"
      end
    end
end

app/helpers/matching_helper.rb
module MatchingHelper
end

app/views/matching/index.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col">
        <div class="user-widget-2">
            <ul class="list-unstyled">
              <% if !@users.empty? %>
                <% @users.each do |user| %>
                <li class="media border-bottom pb-4">
                    <%= link_to(user_path(user)) do %>
                      <% if user.profile.image? %>
                        <%= image_tag user.profile.image.thumb.url, :class => "rounded-circle d-flex align-self-center" %>
                      <% else %>  
                        <img class="rounded-circle d-flex align-self-center" src="../img/noimage.jpg" alt="avatar">
                      <% end %>
                    <% end %>
                    <div class="media-body">
                        <%= link_to(user_path(user), style:'text-decoration: none') do %>
                          <h4 class="mt-2 ml-1"><%= user.profile.username %> <%= user.profile.age %> <%= t '.age' %></h4>
                        <% end %>
                        <% if user.profile.singleword? %>
                          <h5 class="text-dark ml-2"><%= truncate(user.profile.singleword, length: 17) %></h5>
                        <% end %>
                        <p>
                            <span class="mt-2">
                              <%= link_to t('matching.index.chatting'), matching_path(user.id), class:"btn btn-primary btn-sm", style:"text-decoration: none" %>
                            </span>
                            <%= form_for(current_user.active_relationships.find_by(following_id: user.id), html: { method: :delete, class: "mt-2" }) do |f| %>
                              <%= f.submit t('matching.index.delete_matching'), class:"btn btn-primary btn-sm"  %>
                            <% end %>
                        </p>
                    </div>
                </li>
                <% end %>
                <%= paginate @users %>
              <% else %>
                <h4><%= t '.not_matched' %></h4>
              <% end %>
            </ul>
        </div>
    </div>
  </div>
</div>

app/views/matching/show.html.erb
<div class="container">
  <div class="user_pofile border mt-5 mb-0">
    
    <p class="text-white usermess_info mt-3"><%= @user.profile.username %></p>
  </div>
  <% if @user != current_user && user_signed_in? %>
    <section class="message_box" id="po">
      <div id="messages" class="msg_box p-4 rounded">
        <%= render @messages %>
      </div>
    </section>
    
    <div class="message_form mb-5" >
     <%= render 'messages/message_form',
       {from_user: current_user, to_user: @user, room_id: @room_id} %>
    </div>
    
    <script type="text/javascript">
      var obj = document.getElementById("po");
      obj.scrollTop = obj.scrollHeight;
    </script>
  <% end %>
</div>