config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  get 'pages/loginpage'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'users#index'
  
  resources :users do
    member do
     get :following, :followers
    end
  end
  
  resources :matching, only: [:index, :show]
  resources :profiles
  resources :relationships, only: [:index ,:create, :destroy]
  resources :liked, only: [:index]
  mount ActionCable.server => '/cable'
end

app/views/layouts/_footer.html.erb
<footer>
      <div class="container">
        <div class="dropdown mb-4">
          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Languages
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <%= link_to('English', url_for(locale: 'en'), :class => 'dropdown-item') %>
            <%= link_to('日本語', url_for(locale: 'ja'), :class => 'dropdown-item') %>
            <%= link_to('中文', url_for(locale: 'zh'), :class => 'dropdown-item') %>
          </div>
        </div>
        
        <p class="text-white">&copy; My Website 2019. All Rights Reserved.</p>
        <ul class="list-inline">
          <li class="list-inline-item">
            <a href="#" style="color:#fff">Privacy</a>
          </li>
          <li class="list-inline-item">
            <a href="#" style="color:#fff">Terms</a>
          </li>
          <li class="list-inline-item">
            <a href="#" style="color:#fff">FAQ</a>
          </li>
        </ul>
      </div>
      
      
</footer>

app/views/layouts/_navigation.html.erb
<header>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'TAPIOCA', users_path, :class => 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to t('navigation.search'), users_path, :class => 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to t('navigation.like_from'), liked_index_path, :class => 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to t('navigation.list'), matching_index_path, :class => 'nav-link' %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= t'navigation.myaccount' %>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to t('navigation.myprofile'), user_path(current_user), :class => 'dropdown-item' %>
          <%= link_to t('navigation.changeprofile'), edit_profile_path(current_user), :class => 'dropdown-item' %>
          <%= link_to t('navigation.like_to'), relationships_path, :class => 'dropdown-item' %>
          <%= link_to t('navigation.logout'), destroy_user_session_path, method: :delete, :class => 'dropdown-item' %>
          <div class="dropdown-divider"></div>
          <%= link_to t('navigation.setting'), '#', :class => 'dropdown-item' %>
        </div>
      </li>
    </ul>
  </div>
  
</nav>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title)%></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800"%>
    <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
    
  <body>
    <% if user_signed_in? %>
      <%= render 'layouts/navigation' %>
    <% end %>
    <% unless notice.nil? %>
      <p class="notice"><%= notice %></p>
    <% end %>
    <% unless alert.nil? %>
      <p class="alert"><%= alert %></p>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <script src="//cdn.jsdelivr.net/mojs/latest/mo.min.js"></script>
    <!-- For js, so it's possible that other ajax doesn't work by this change -->
  </body>
</html>